# Generated by Django 4.0.4 on 2022-04-30 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('crm', models.CharField(max_length=13, null=True)),
                ('postal_code', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=150)),
                ('address_number', models.CharField(max_length=7)),
                ('complement', models.CharField(max_length=70, null=True)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=150)),
                ('tel1', models.CharField(max_length=11)),
                ('tel2', models.CharField(max_length=11, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_creator_set', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='specialty.specialty')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_updater_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
