# Generated by Django 4.0.4 on 2022-04-30 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_active_alter_employee_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lunch_finish_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='lunch_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
