# Generated by Django 4.0.4 on 2022-06-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_end_time_employee_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
