# Generated by Django 4.0.4 on 2022-06-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_end_time_alter_employee_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='end_time',
            new_name='finish_time',
        ),
    ]
