# Generated by Django 4.0.4 on 2022-04-30 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_employee_active_alter_employee_creator_and_more'),
        ('specialty', '0002_specialty_active_alter_specialty_creator_and_more'),
        ('customer', '0002_customer_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('appointment_return', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('justification', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_creator_set', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialty.specialty')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_updater_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
