# Generated by Django 4.0.4 on 2022-05-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('appointment_date', 'appointment_time', 'specialty', 'doctor', 'customer')},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='hour',
            new_name='appointment_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
