# Generated by Django 4.0.4 on 2022-05-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('c_co', 'Não compareceu'), ('age', 'Agendado'), ('agu', 'Aguardando'), ('can', 'Cancelado'), ('ret', 'Retorno')], default='age', max_length=100),
        ),
    ]
