# Generated by Django 4.0.4 on 2022-05-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('nac', 'Não compareceu'), ('age', 'Agendado'), ('agu', 'Aguardando'), ('can', 'Cancelado'), ('ret', 'Retorno'), ('fin', 'Finalizado')], default='age', max_length=100),
        ),
    ]
