# Generated by Django 4.0.4 on 2022-05-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='days_number_to_search',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='duration_consultation',
            field=models.IntegerField(default=30),
        ),
    ]
