# Generated by Django 4.0.4 on 2022-05-17 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0002_clinic_days_number_to_search_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='duration_consultation',
            new_name='consultation_duration',
        ),
        migrations.AddField(
            model_name='clinic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clinic_creator_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='updater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clinic_updater_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
