# Generated by Django 4.0.4 on 2022-04-30 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_creator_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_updater_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
