# Generated by Django 4.0.4 on 2022-05-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0002_specialty_active_alter_specialty_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='description',
            field=models.TextField(default='Description of specialty', max_length=400),
        ),
    ]
