# Generated by Django 4.0.4 on 2022-05-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pen', 'Pendente'), ('eat', 'Em andamento'), ('fin', 'Finalizado')], default='pen', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medical_chart',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
