# Generated by Django 4.0.4 on 2022-05-30 22:25

import consultation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_consultation_status_alter_consultation_medical_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='medical_chart',
            field=models.FileField(blank=True, null=True, upload_to=consultation.models.Consultation.get_upload_path),
        ),
    ]
